### ISSUE TITLE
`narn run`

### ISSUE THREAD

**Issue by paulirish** [joeldenning/narn#21]
I use `npm run` or `yarn run` often to get a listing of all the scripts.

`narn run` runs `npm run run` which fails.

```
❯ narn run
npm run run
npm ERR! missing script: run
```

**Comment by joeldenning** [comment]
👍 thanks for the report. This should be an easy one to fix.

**Comment by joeldenning** [comment]
Fix released in https://github.com/joeldenning/narn/releases/tag/v1.9.0

**Comment by paulirish** [comment]
lol. Funny story.

Today I was thinking to myself....

> man i think i still have this bug. i run `narn run` and in yarn repos its fine, but not in npm repos... it's cranky and i don't get the script list. 
> /me runs `narn --version`. 1.8.0. huh. is that pretty old?
> /me opens https://github.com/joeldenning/narn and sees we're up to 2.3.0
> sweet. i'll upgrade my narn
> /me tries again. works!!  sweet. i imagine someone reported this and it got fixed.  
> hmmm i'm curious.. who also ran into this?
> /me finds this issue. OH IT WAS ME
> and god damn it joel fixed it SAME DAY! and published a new release. SAME DAY
> and yet ive been dealing with this bug for an extra 29 months. because i didnt notice your timely replies. WHOOOOOOOPS.

anyway..

thanks Joel for being an awesome maintainer. :)
